#!/usr/bin/env bash
# Generate extension/config.js from current Hypha env (HYPHA_SERVER_URL,
# HYPHA_WORKSPACE, HYPHA_TOKEN). Never commit the output.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"

: "${HYPHA_SERVER_URL:=https://hypha.aicell.io}"
: "${HYPHA_WORKSPACE:?HYPHA_WORKSPACE not set}"
: "${HYPHA_TOKEN:?HYPHA_TOKEN not set}"

SERVICE_ID="${1:-browser-controller}"

# Escape any single quotes in the token (paranoid; tokens are usually base64-safe)
esc() { printf '%s' "$1" | sed "s/'/\\\\'/g"; }

cat > "$ROOT/extension/config.js" <<EOF
// Generated by scripts/build-config.sh. DO NOT COMMIT.
export const HYPHA_CONFIG = {
  server_url: '$(esc "$HYPHA_SERVER_URL")',
  workspace: '$(esc "$HYPHA_WORKSPACE")',
  token: '$(esc "$HYPHA_TOKEN")',
  service_id: '$(esc "$SERVICE_ID")',
  service_name: 'Browser Controller',
  visibility: 'public',
};
EOF

echo "Wrote extension/config.js"
echo "  server: $HYPHA_SERVER_URL"
echo "  workspace: $HYPHA_WORKSPACE"
echo "  service_id: $SERVICE_ID"
echo "  token: ($(echo -n "$HYPHA_TOKEN" | wc -c | tr -d ' ') bytes)"
